// Re-export all types from the orval-generated schemas (single source of truth).
// After `make codegen`, this file is the only place components need to import from.
export * from '../generated/schemas'

// Backward-compat alias: generated uses TestRunnerTree, existing code uses TestRunTree.
export type { TestRunnerTree as TestRunTree } from '../generated/schemas'

// FlameGraphCategory is kept as a plain string union for use as Record key.
// The generated FlameGraphNodeCategory is a const-enum with the same values.
export type FlameGraphCategory =
  | 'controller'
  | 'view'
  | 'partial'
  | 'sql'
  | 'cache'
  | 'http'
  | 'custom'
  | 'method'

// TestData captures test-level profiling results stored in collectors_data.test.
// It is not exposed as a standalone API endpoint and therefore not generated by orval.
export interface TestData {
  test_name: string
  status: string
  test_file: string
  test_line: number
  framework: string
  assertions?: number
  skip_reason?: string
  exception_message?: string
}

// FunctionProfileData and FunctionStat capture function-level profiling results
// stored in collectors_data.function_profile. They are not exposed as standalone
// API endpoints and therefore not generated by orval.
export interface FunctionStat {
  name: string
  file: string
  line: number
  calls: number
  recursive_calls: number
  total_duration: number
  self_duration: number
  allocated_objects: number
  memory_bytes: number
  self_memory_bytes: number
}

export interface FunctionProfileData {
  enabled: boolean
  mode?: 'full' | 'lite'
  clock?: 'wall' | 'cpu' | 'object'
  elapsed_wall_ms?: number
  elapsed_cpu_ms?: number
  gc_samples?: number
  gc_overhead_pct?: number
  max_frames?: number
  frame_cap_reached?: boolean
  total_calls?: number
  total_duration?: number
  total_allocated_objects?: number
  total_memory_bytes?: number
  functions?: FunctionStat[]
  root_calls?: import('../generated/schemas/flameGraphNode').FlameGraphNode[]
}
