# frozen_string_literal: true

require_relative "../../../lib/profiler/cluster/security"

module Profiler
  class ApplicationController < ActionController::Base
    layout "profiler/application"

    # A store that cannot be created: the cause in one line, as a 503, for every page and API.
    rescue_from Profiler::Storage::Unavailable::Error, with: :storage_unavailable

    before_action :check_authorization
    before_action :authorize_request
    # Declared after the access checks, so that an unauthorized request gets its 403 first.
    protect_from_forgery with: :exception

    private

    def check_authorization
      deny("Profiler is disabled") unless Profiler.configuration.enabled
    end

    def authorize_request
      # Checked first, so that :allow_local does not log a refusal for the master's calls.
      return if cluster_master_request?
      return if Profiler.configuration.authorized?(request)

      deny("Not authorized to access the profiler")
    end

    # Decided by the profiler's own setting, not by the application's allow_forgery_protection,
    # which the config/environments/test.rb generated by Rails turns off.
    def protect_against_forgery?
      Profiler.configuration.api_forgery_protection ? true : false
    end

    # Rails' token, or the header every profiler client sends. A third-party page cannot add a
    # custom header without a CORS preflight, which is refused unless an origin was allowed.
    def verified_request?
      super || request.headers[Profiler::FORGERY_PROTECTION_HEADER].present? || cluster_master_request?
    end

    # On a slave, the master's proxied calls carry the shared secret, which stands for both the
    # access guard and the forgery header. Never true on a node without master_url, or without
    # a configured secret.
    def cluster_master_request?
      Profiler.configuration.slave? && Cluster::Security.request_secret_valid?(request)
    end

    def handle_unverified_request
      deny("Missing #{Profiler::FORGERY_PROTECTION_HEADER} header or CSRF token")
    end

    def storage_unavailable(error)
      if controller_path.start_with?("profiler/api/")
        render json: { error: error.message }, status: :service_unavailable
      else
        render plain: error.message, status: :service_unavailable
      end
    end

    def deny(message)
      if controller_path.start_with?("profiler/api/")
        render json: { error: message }, status: :forbidden
      else
        render plain: message, status: :forbidden
      end
    end

    # A page of one type of profile, filtered, ordered and paged by the store: one profile more
    # than the limit tells whether there is a next page, at any offset.
    def render_profile_page(type:, summary: true)
      limit, offset = page_params
      render_page(Profiler.storage.list(limit: limit + 1, offset: offset, type: type, summary: summary), limit, offset)
    end

    # The bodies as text: the cluster proxy lists whole profiles (all_types), a summary has none.
    def render_page(profiles, limit, offset)
      render json: {
        profiles: profiles.first(limit).map { |profile| profile.to_h(decode_bodies: true) },
        limit:    limit,
        offset:   offset,
        has_more: profiles.size > limit
      }
    end

    def page_params
      [[(params[:limit] || 50).to_i, 0].max, [(params[:offset] || 0).to_i, 0].max]
    end

    # The children of a page, read once per request: the child jobs and the AJAX tab share them.
    def child_profiles(profile)
      @child_profiles ||= {}
      @child_profiles[profile.token] ||= (@resolved_storage || Profiler.storage).find_by_parent(profile.token)
    end

    # The AJAX sub-requests are saved after the page: their tab is computed here, whatever the
    # configured collector list (Profiler::AjaxData).
    def recalculate_ajax_data(profile)
      Profiler::AjaxData.attach(profile, child_profiles(profile))
    end

    def build_child_jobs(profile)
      child_profiles(profile).select { |p| p.profile_type == "job" }.map do |j|
        job_data = j.collector_data("job") || {}
        {
          token: j.token,
          job_class: j.path,
          job_id: job_data["job_id"],
          queue: job_data["queue"],
          status: job_data["status"],
          duration: j.duration,
          started_at: j.started_at&.iso8601
        }
      end
    end

    def build_parent_summary(profile)
      return nil unless profile.parent_token

      storage = @resolved_storage || Profiler.storage
      parent  = storage.load(profile.parent_token)
      # Cross-node fallback: parent may live on the master when the profile is on a slave
      parent ||= Profiler.storage.load(profile.parent_token) if storage != Profiler.storage
      return nil unless parent

      if parent.profile_type == "job"
        job_data = parent.collector_data("job") || {}
        {
          token: parent.token,
          profile_type: "job",
          path: parent.path,
          status: job_data["status"],
          duration: parent.duration,
          started_at: parent.started_at&.iso8601
        }
      else
        {
          token: parent.token,
          profile_type: "http",
          method: parent.method,
          path: parent.path,
          http_status: parent.status,
          duration: parent.duration,
          started_at: parent.started_at&.iso8601
        }
      end
    end
  end
end
