# frozen_string_literal: true

require_relative "../../../lib/profiler/cluster/security"

module Profiler
  class ApplicationController < ActionController::Base
    layout "profiler/application"

    before_action :check_authorization
    before_action :authorize_request
    # Declared after the access checks, so that an unauthorized request gets its 403 first.
    protect_from_forgery with: :exception

    private

    def check_authorization
      unless Profiler.configuration.enabled
        render plain: "Profiler is disabled", status: :forbidden
      end
    end

    def authorize_request
      # Checked first, so that :allow_local does not log a refusal for the master's calls.
      return if cluster_master_request?
      return if Profiler.configuration.authorized?(request)

      deny("Not authorized to access the profiler")
    end

    # Decided by the profiler's own setting, not by the application's allow_forgery_protection,
    # which the config/environments/test.rb generated by Rails turns off.
    def protect_against_forgery?
      Profiler.configuration.api_forgery_protection ? true : false
    end

    # Rails' token, or the header every profiler client sends. A third-party page cannot add a
    # custom header without a CORS preflight, which is refused unless an origin was allowed.
    def verified_request?
      super || request.headers[Profiler::FORGERY_PROTECTION_HEADER].present? || cluster_master_request?
    end

    # On a slave, the master's proxied calls carry the shared secret, which stands for both the
    # access guard and the forgery header. Never true on a node without master_url, or without
    # a configured secret.
    def cluster_master_request?
      Profiler.configuration.slave? && Cluster::Security.request_secret_valid?(request)
    end

    def handle_unverified_request
      deny("Missing #{Profiler::FORGERY_PROTECTION_HEADER} header or CSRF token")
    end

    def deny(message)
      if controller_path.start_with?("profiler/api/")
        render json: { error: message }, status: :forbidden
      else
        render plain: message, status: :forbidden
      end
    end

    def build_child_jobs(profile)
      storage = @resolved_storage || Profiler.storage
      storage.find_by_parent(profile.token)
             .select { |p| p.profile_type == "job" }
             .map do |j|
               job_data = j.collector_data("job") || {}
               {
                 token: j.token,
                 job_class: j.path,
                 job_id: job_data["job_id"],
                 queue: job_data["queue"],
                 status: job_data["status"],
                 duration: j.duration,
                 started_at: j.started_at&.iso8601
               }
             end
    end

    def build_parent_summary(profile)
      return nil unless profile.parent_token

      storage = @resolved_storage || Profiler.storage
      parent  = storage.load(profile.parent_token)
      # Cross-node fallback: parent may live on the master when the profile is on a slave
      parent ||= Profiler.storage.load(profile.parent_token) if storage != Profiler.storage
      return nil unless parent

      if parent.profile_type == "job"
        job_data = parent.collector_data("job") || {}
        {
          token: parent.token,
          profile_type: "job",
          path: parent.path,
          status: job_data["status"],
          duration: parent.duration,
          started_at: parent.started_at&.iso8601
        }
      else
        {
          token: parent.token,
          profile_type: "http",
          method: parent.method,
          path: parent.path,
          http_status: parent.status,
          duration: parent.duration,
          started_at: parent.started_at&.iso8601
        }
      end
    end
  end
end
